apiVersion: operator.ibm.com/v1alpha1
kind: MongoDB
metadata:
  name: ibm-mongodb
  labels:
    app.kubernetes.io/instance: mongodbs.operator.ibm.com
    app.kubernetes.io/managed-by: mongodbs.operator.ibm.com
    app.kubernetes.io/name: mongodbs.operator.ibm.com
spec:
  replicas: 3
  fsgroup: 13001
